### ISSUE TITLE
d3 layout cloud react integration and svg position

### ISSUE THREAD

**Issue by KrysD** [KrysD/wordCloud#1]
@iOiurson, 

I create an un reactive word cloud to represent the names list of the previous training.

I have problem drawing all the words. 
![image](https://cloud.githubusercontent.com/assets/13766508/12680982/b530e46c-c6ac-11e5-8d0b-d641aa50d356.png)

The only solution i found to draw all the words is to reduce the word font size, to ensure the words fit in the svg or increase the size of svg.
see [here](https://github.com/KrysD/wordCloud/blob/1519b4cd965044b78400fe7a0f39890cf64b907b/main.js#L41-L42) 
So i would like to knwo how tomove the cloud on the center of the body and attribute to the cloud the entire width and height ?

Then i would like to include this code inside the react example we have done. Did i you think it will be easy to make it with react and redraw the cloud depending on the years and sexe selection ?

**Comment by bleucitron** [comment]
You should check out my PR before merging. To do so, you have CLI infos at the bottom of the PR.
Basically, it's just:
- checking out to a new branch for PR revision
- `git pull` the branch of my remote repo
- verify that my code actually works
- merge the PR if you're satisfied, comment the PR if you're not.

Concerning the React integration, it will be super easy, as long as you regenerate your cloud with the filtered names.
You could imagine a React component whose only purpose is to render a list of names passed as props. The filtering would be done as we did together on our training session.
